####################################################
# This sanoid.conf file should go in /etc/sanoid.  #
####################################################

## name your backup modules with the path to their ZFS dataset - no leading slash.
#[zpoolname/datasetname]
#	# pick one or more templates - they're defined (and editable) below. Comma separated, processed in order.

[fast200]
	use_template = production
	recursive = yes

[fast200/_VMs]
	use_template = production
	recursive = yes

[rpool/_Backup]
	use_template = backup
	recursive = yes

[rpool/_Shadows]
	use_template = shadows
	recursive = yes

[rpool/_VMs]
	use_template = production
	recursive = yes

#############################
# templates below this line #
#############################

# name your templates template_templatename.

[template_production]
	frequently = 4
	hourly = 36
	daily = 15
	monthly = 2
	yearly = 0
	autosnap = yes
	autoprune = yes

[template_backup]
	autosnap = yes
	autoprune = yes
	frequently = 0
	hourly = 30
	daily = 21
	monthly = 12
	yearly = 2

	### monitor hourlies and dailies, but don't warn or
	### crit until they're over 48h old, since replication
	### is typically daily only
	hourly_warn = 2880
	hourly_crit = 3600
	daily_warn = 48
	daily_crit = 60

[template_shadows]
	autoprune = yes
	frequently = 0
	hourly = 30
	daily = 21
	monthly = 7
	yearly = 0

	### don't take new snapshots - snapshots on backup
	### datasets are replicated in from source, not
	### generated locally
	autosnap = no

	hourly_warn = 2880
	hourly_crit = 3600
	daily_warn = 48
	daily_crit = 60

[template_hotspare]
	autosnap = no
	autoprune = yes
	frequently = 0
	hourly = 30
	daily = 9
	monthly = 0
	yearly = 0

	hourly_warn = 4h
	hourly_crit = 6h
	daily_warn = 2d
	daily_crit = 4d

[template_scripts]
	### information about the snapshot will be supplied as environment variables,
	### see the README.md file for details about what is passed when.
	script_timeout = 5

[template_ignore]
	autoprune = no
	autosnap = no
	monitor = no

